from __future__ import annotations

import ast
import json
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable


REPO_ROOT = Path(__file__).resolve().parents[1]
EXAMPLES_ROOT = REPO_ROOT / "examples"
OUTPUT_ROOT = REPO_ROOT / "specs" / "examples"


@dataclass
class ExampleSpec:
    category: str
    module_name: str
    relative_path: str
    has_run_all_examples: bool
    uses_config_helpers: bool
    operation_functions: list[str]
    docstring: str


@dataclass
class ParseError:
    relative_path: str
    error: str


def iter_example_files() -> Iterable[Path]:
    for file_path in sorted(EXAMPLES_ROOT.rglob("*.py")):
        if file_path.name == "config.py":
            continue
        yield file_path


def parse_module(file_path: Path) -> ExampleSpec:
    source = file_path.read_text(encoding="utf-8")
    tree = ast.parse(source, filename=str(file_path))

    functions = [
        node.name
        for node in tree.body
        if isinstance(node, ast.FunctionDef)
    ]
    operation_functions = [name for name in functions if name != "run_all_examples"]

    uses_config_helpers = False
    for node in tree.body:
        if isinstance(node, ast.ImportFrom) and node.module == "config":
            imported_names = {alias.name for alias in node.names}
            if {"set_license", "initialize_data_dir"}.issubset(imported_names):
                uses_config_helpers = True
                break

    relative_path = file_path.relative_to(REPO_ROOT).as_posix()
    relative_examples_path = file_path.relative_to(EXAMPLES_ROOT)
    category = relative_examples_path.parts[0] if len(relative_examples_path.parts) > 1 else "root"

    docstring = ast.get_docstring(tree) or ""
    docstring = docstring.strip().splitlines()[0] if docstring.strip() else ""

    return ExampleSpec(
        category=category,
        module_name=file_path.stem,
        relative_path=relative_path,
        has_run_all_examples="run_all_examples" in functions,
        uses_config_helpers=uses_config_helpers,
        operation_functions=operation_functions,
        docstring=docstring,
    )


def render_markdown(specs: list[ExampleSpec]) -> str:
    lines = [
        "# Example Specs",
        "",
        "Generated by `python scripts/generate_example_specs.py`.",
        "",
        f"Total modules: {len(specs)}",
        "",
        "| Category | Module | Path | `run_all_examples` | Config helpers | Operations |",
        "| --- | --- | --- | --- | --- | --- |",
    ]

    for spec in specs:
        operations = ", ".join(spec.operation_functions) if spec.operation_functions else "-"
        lines.append(
            f"| {spec.category} | {spec.module_name} | `{spec.relative_path}` | "
            f"{'yes' if spec.has_run_all_examples else 'no'} | "
            f"{'yes' if spec.uses_config_helpers else 'no'} | {operations} |"
        )

    return "\n".join(lines) + "\n"


def render_errors_markdown(errors: list[ParseError]) -> list[str]:
    if not errors:
        return []

    lines = [
        "",
        "## Parse Errors",
        "",
        "| Path | Error |",
        "| --- | --- |",
    ]
    for error in errors:
        lines.append(f"| `{error.relative_path}` | {error.error} |")
    return lines


def main() -> None:
    specs: list[ExampleSpec] = []
    errors: list[ParseError] = []
    for file_path in iter_example_files():
        try:
            specs.append(parse_module(file_path))
        except SyntaxError as exc:
            errors.append(
                ParseError(
                    relative_path=file_path.relative_to(REPO_ROOT).as_posix(),
                    error=f"{exc.__class__.__name__}: {exc.msg} (line {exc.lineno})",
                )
            )

    OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)

    index_json_path = OUTPUT_ROOT / "index.json"
    index_md_path = OUTPUT_ROOT / "index.md"

    payload = {
        "generated_from": str(EXAMPLES_ROOT.relative_to(REPO_ROOT)).replace("\\", "/"),
        "total_modules": len(specs),
        "modules": [asdict(spec) for spec in specs],
        "parse_errors": [asdict(error) for error in errors],
    }

    index_json_path.write_text(
        json.dumps(payload, indent=2, ensure_ascii=True) + "\n",
        encoding="utf-8",
    )

    markdown = render_markdown(specs).rstrip("\n").splitlines()
    markdown.extend(render_errors_markdown(errors))
    index_md_path.write_text("\n".join(markdown) + "\n", encoding="utf-8")

    print(f"Wrote {index_json_path.relative_to(REPO_ROOT)}")
    print(f"Wrote {index_md_path.relative_to(REPO_ROOT)}")
    if errors:
        print(f"Skipped {len(errors)} files with syntax errors")


if __name__ == "__main__":
    main()
